/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * satnav navigation data bit subframe.
 */
public final class measurement_satnav_subframe implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_measurement_satnav_subframe;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    public aspn23_lcm.type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    public aspn23_lcm.type_timestamp time_of_validity;

    /**
     * Description: Message ID provided from the satnav receiver.
     * Units: none
     */
    public long gnss_message_id;

    /**
     * Description: Satellite ID number.
     * Units: none
     */
    public int prn;

    /**
     * Description: Describes the satellite system that generated the subframe.
     * Units: none
     */
    public aspn23_lcm.type_satnav_satellite_system satellite_system;

    /**
     * Description: Frequency slot +7 (range from 0-13). Only used for GLONASS.
     * Units: none
     */
    public int freq_slot_id;

    /**
     * Description: Number of bytes of subframe data.
     * Units: none
     */
    public int num_bytes;

    /**
     * Description: num_bytes sized array of raw subframe message collected by the sensor. The
     * underlying type and shape of the data vector is given by satnav_msg_id.
     * Units: none
     * LCM Type: byte[num_bytes]
     */
    public byte data_vector[];

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    public short num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    public aspn23_lcm.type_integrity integrity[];

 
    public measurement_satnav_subframe()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x15322dda6d63e750L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.measurement_satnav_subframe.class))
            return 0L;
 
        classes.add(aspn23_lcm.measurement_satnav_subframe.class);
        long hash = LCM_FINGERPRINT_BASE
             + aspn23_lcm.type_header._hashRecursive(classes)
             + aspn23_lcm.type_timestamp._hashRecursive(classes)
             + aspn23_lcm.type_satnav_satellite_system._hashRecursive(classes)
             + aspn23_lcm.type_integrity._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_measurement_satnav_subframe); 
 
        this.header._encodeRecursive(outs); 
 
        this.time_of_validity._encodeRecursive(outs); 
 
        outs.writeLong(this.gnss_message_id); 
 
        outs.writeInt(this.prn); 
 
        this.satellite_system._encodeRecursive(outs); 
 
        outs.writeInt(this.freq_slot_id); 
 
        outs.writeInt(this.num_bytes); 
 
        if (this.num_bytes > 0)
            outs.write(this.data_vector, 0, (int) num_bytes);
 
        outs.writeShort(this.num_integrity); 
 
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a]._encodeRecursive(outs); 
        }
 
    }
 
    public measurement_satnav_subframe(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public measurement_satnav_subframe(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.measurement_satnav_subframe _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.measurement_satnav_subframe o = new aspn23_lcm.measurement_satnav_subframe();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_measurement_satnav_subframe = ins.readByte();
 
        this.header = aspn23_lcm.type_header._decodeRecursiveFactory(ins);
 
        this.time_of_validity = aspn23_lcm.type_timestamp._decodeRecursiveFactory(ins);
 
        this.gnss_message_id = ins.readLong();
 
        this.prn = ins.readInt();
 
        this.satellite_system = aspn23_lcm.type_satnav_satellite_system._decodeRecursiveFactory(ins);
 
        this.freq_slot_id = ins.readInt();
 
        this.num_bytes = ins.readInt();
 
        this.data_vector = new byte[(int) num_bytes];
        ins.readFully(this.data_vector, 0, (int) num_bytes); 
        this.num_integrity = ins.readShort();
 
        this.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a] = aspn23_lcm.type_integrity._decodeRecursiveFactory(ins);
        }
 
    }
 
    public aspn23_lcm.measurement_satnav_subframe copy()
    {
        aspn23_lcm.measurement_satnav_subframe outobj = new aspn23_lcm.measurement_satnav_subframe();
        outobj.icd_measurement_satnav_subframe = this.icd_measurement_satnav_subframe;
 
        outobj.header = this.header.copy();
 
        outobj.time_of_validity = this.time_of_validity.copy();
 
        outobj.gnss_message_id = this.gnss_message_id;
 
        outobj.prn = this.prn;
 
        outobj.satellite_system = this.satellite_system.copy();
 
        outobj.freq_slot_id = this.freq_slot_id;
 
        outobj.num_bytes = this.num_bytes;
 
        outobj.data_vector = new byte[(int) num_bytes];
        if (this.num_bytes > 0)
            System.arraycopy(this.data_vector, 0, outobj.data_vector, 0, (int) this.num_bytes); 
        outobj.num_integrity = this.num_integrity;
 
        outobj.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            outobj.integrity[a] = this.integrity[a].copy();
        }
 
        return outobj;
    }
 
}

