/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Image feature characteristics
 */
public final class type_image_feature implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_type_image_feature;

    /**
     * Description: Value representing the magnitude of the response of the keypoint detection
     * algorithm used to locate this keypoint in the image.
     * Units: none
     */
    public double response;

    /**
     * Description: Value representing the orientation of the detected keypoint, as measured relative
     * to the image coordinate system (radians, clockwise). Metadata flag determines if this field is
     * calculated by the current keypoint detector.
     * Units: rad
     */
    public double orientation;

    /**
     * Description: Effective size (pixels) of the detected keypoint. This field takes into
     * consideration the octave and kernel used to localize the keypoint, and normalizes to the original
     * size of the image.
     * Units: pixels
     */
    public double size;

    /**
     * Description: ID that ties the detected keypoint to a class or group of keypoints.
     * Units: none
     */
    public int class_id;

    /**
     * Description: Octave or pyramid layer from which the detected keypoint was extracted.
     * Units: none
     */
    public int octave;

    /**
     * Description: Size of the descriptor in bytes.
     * Units: none
     */
    public int descriptor_size;

    /**
     * Description: Feature descriptor.
     * Units: none
     * LCM Type: byte[descriptor_size]
     */
    public byte descriptor[];

 
    public type_image_feature()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb7044cccc86ac036L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.type_image_feature.class))
            return 0L;
 
        classes.add(aspn23_lcm.type_image_feature.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_type_image_feature); 
 
        outs.writeDouble(this.response); 
 
        outs.writeDouble(this.orientation); 
 
        outs.writeDouble(this.size); 
 
        outs.writeInt(this.class_id); 
 
        outs.writeInt(this.octave); 
 
        outs.writeInt(this.descriptor_size); 
 
        if (this.descriptor_size > 0)
            outs.write(this.descriptor, 0, (int) descriptor_size);
 
    }
 
    public type_image_feature(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public type_image_feature(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.type_image_feature _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.type_image_feature o = new aspn23_lcm.type_image_feature();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_type_image_feature = ins.readByte();
 
        this.response = ins.readDouble();
 
        this.orientation = ins.readDouble();
 
        this.size = ins.readDouble();
 
        this.class_id = ins.readInt();
 
        this.octave = ins.readInt();
 
        this.descriptor_size = ins.readInt();
 
        this.descriptor = new byte[(int) descriptor_size];
        ins.readFully(this.descriptor, 0, (int) descriptor_size); 
    }
 
    public aspn23_lcm.type_image_feature copy()
    {
        aspn23_lcm.type_image_feature outobj = new aspn23_lcm.type_image_feature();
        outobj.icd_type_image_feature = this.icd_type_image_feature;
 
        outobj.response = this.response;
 
        outobj.orientation = this.orientation;
 
        outobj.size = this.size;
 
        outobj.class_id = this.class_id;
 
        outobj.octave = this.octave;
 
        outobj.descriptor_size = this.descriptor_size;
 
        outobj.descriptor = new byte[(int) descriptor_size];
        if (this.descriptor_size > 0)
            System.arraycopy(this.descriptor, 0, outobj.descriptor, 0, (int) this.descriptor_size); 
        return outobj;
    }
 
}

