// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#include <string.h>
#include "aspn23_lcm_measurement_image.h"

static int __aspn23_lcm_measurement_image_hash_computed;
static uint64_t __aspn23_lcm_measurement_image_hash;

uint64_t __aspn23_lcm_measurement_image_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __aspn23_lcm_measurement_image_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __aspn23_lcm_measurement_image_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xb9911e5964b761c2LL
         + __int8_t_hash_recursive(&cp)
         + __aspn23_lcm_type_header_hash_recursive(&cp)
         + __aspn23_lcm_type_timestamp_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __aspn23_lcm_type_integrity_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __aspn23_lcm_measurement_image_get_hash(void)
{
    if (!__aspn23_lcm_measurement_image_hash_computed) {
        __aspn23_lcm_measurement_image_hash = (int64_t)__aspn23_lcm_measurement_image_hash_recursive(NULL);
        __aspn23_lcm_measurement_image_hash_computed = 1;
    }

    return __aspn23_lcm_measurement_image_hash;
}

int __aspn23_lcm_measurement_image_encode_array(void *buf, int offset, int maxlen, const aspn23_lcm_measurement_image *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].icd_measurement_image), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __aspn23_lcm_type_header_encode_array(buf, offset + pos, maxlen - pos, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __aspn23_lcm_type_timestamp_encode_array(buf, offset + pos, maxlen - pos, &(p[element].time_of_validity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_bigendian), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_type), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_data_length), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].image_data, p[element].image_data_length);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].camera_model), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_model_coefficients), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].model_coefficients, p[element].num_model_coefficients);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_integrity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __aspn23_lcm_type_integrity_encode_array(buf, offset + pos, maxlen - pos, p[element].integrity, p[element].num_integrity);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int aspn23_lcm_measurement_image_encode(void *buf, int offset, int maxlen, const aspn23_lcm_measurement_image *p)
{
    int pos = 0, thislen;
    int64_t hash = __aspn23_lcm_measurement_image_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __aspn23_lcm_measurement_image_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __aspn23_lcm_measurement_image_encoded_array_size(const aspn23_lcm_measurement_image *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int8_t_encoded_array_size(&(p[element].icd_measurement_image), 1);

        size += __aspn23_lcm_type_header_encoded_array_size(&(p[element].header), 1);

        size += __aspn23_lcm_type_timestamp_encoded_array_size(&(p[element].time_of_validity), 1);

        size += __int64_t_encoded_array_size(&(p[element].height), 1);

        size += __int64_t_encoded_array_size(&(p[element].width), 1);

        size += __boolean_encoded_array_size(&(p[element].is_bigendian), 1);

        size += __int8_t_encoded_array_size(&(p[element].image_type), 1);

        size += __int64_t_encoded_array_size(&(p[element].image_data_length), 1);

        size += __byte_encoded_array_size(p[element].image_data, p[element].image_data_length);

        size += __int8_t_encoded_array_size(&(p[element].camera_model), 1);

        size += __int16_t_encoded_array_size(&(p[element].num_model_coefficients), 1);

        size += __double_encoded_array_size(p[element].model_coefficients, p[element].num_model_coefficients);

        size += __int16_t_encoded_array_size(&(p[element].num_integrity), 1);

        size += __aspn23_lcm_type_integrity_encoded_array_size(p[element].integrity, p[element].num_integrity);

    }
    return size;
}

int aspn23_lcm_measurement_image_encoded_size(const aspn23_lcm_measurement_image *p)
{
    return 8 + __aspn23_lcm_measurement_image_encoded_array_size(p, 1);
}

int __aspn23_lcm_measurement_image_decode_array(const void *buf, int offset, int maxlen, aspn23_lcm_measurement_image *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].icd_measurement_image), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __aspn23_lcm_type_header_decode_array(buf, offset + pos, maxlen - pos, &(p[element].header), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __aspn23_lcm_type_timestamp_decode_array(buf, offset + pos, maxlen - pos, &(p[element].time_of_validity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_bigendian), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_type), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_data_length), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].image_data = (uint8_t*) lcm_malloc(sizeof(uint8_t) * p[element].image_data_length);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].image_data, p[element].image_data_length);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].camera_model), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_model_coefficients), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].model_coefficients = (double*) lcm_malloc(sizeof(double) * p[element].num_model_coefficients);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].model_coefficients, p[element].num_model_coefficients);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_integrity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].integrity = (aspn23_lcm_type_integrity*) lcm_malloc(sizeof(aspn23_lcm_type_integrity) * p[element].num_integrity);
        thislen = __aspn23_lcm_type_integrity_decode_array(buf, offset + pos, maxlen - pos, p[element].integrity, p[element].num_integrity);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __aspn23_lcm_measurement_image_decode_array_cleanup(aspn23_lcm_measurement_image *p, int elements)
{
    (void)p;
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_decode_array_cleanup(&(p[element].icd_measurement_image), 1);

        __aspn23_lcm_type_header_decode_array_cleanup(&(p[element].header), 1);

        __aspn23_lcm_type_timestamp_decode_array_cleanup(&(p[element].time_of_validity), 1);

        __int64_t_decode_array_cleanup(&(p[element].height), 1);

        __int64_t_decode_array_cleanup(&(p[element].width), 1);

        __boolean_decode_array_cleanup(&(p[element].is_bigendian), 1);

        __int8_t_decode_array_cleanup(&(p[element].image_type), 1);

        __int64_t_decode_array_cleanup(&(p[element].image_data_length), 1);

        __byte_decode_array_cleanup(p[element].image_data, p[element].image_data_length);
        if (p[element].image_data) free(p[element].image_data);

        __int8_t_decode_array_cleanup(&(p[element].camera_model), 1);

        __int16_t_decode_array_cleanup(&(p[element].num_model_coefficients), 1);

        __double_decode_array_cleanup(p[element].model_coefficients, p[element].num_model_coefficients);
        if (p[element].model_coefficients) free(p[element].model_coefficients);

        __int16_t_decode_array_cleanup(&(p[element].num_integrity), 1);

        __aspn23_lcm_type_integrity_decode_array_cleanup(p[element].integrity, p[element].num_integrity);
        if (p[element].integrity) free(p[element].integrity);

    }
    return 0;
}

int aspn23_lcm_measurement_image_decode(const void *buf, int offset, int maxlen, aspn23_lcm_measurement_image *p)
{
    int pos = 0, thislen;
    int64_t hash = __aspn23_lcm_measurement_image_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __aspn23_lcm_measurement_image_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int aspn23_lcm_measurement_image_decode_cleanup(aspn23_lcm_measurement_image *p)
{
    return __aspn23_lcm_measurement_image_decode_array_cleanup(p, 1);
}

int __aspn23_lcm_measurement_image_clone_array(const aspn23_lcm_measurement_image *p, aspn23_lcm_measurement_image *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_clone_array(&(p[element].icd_measurement_image), &(q[element].icd_measurement_image), 1);

        __aspn23_lcm_type_header_clone_array(&(p[element].header), &(q[element].header), 1);

        __aspn23_lcm_type_timestamp_clone_array(&(p[element].time_of_validity), &(q[element].time_of_validity), 1);

        __int64_t_clone_array(&(p[element].height), &(q[element].height), 1);

        __int64_t_clone_array(&(p[element].width), &(q[element].width), 1);

        __boolean_clone_array(&(p[element].is_bigendian), &(q[element].is_bigendian), 1);

        __int8_t_clone_array(&(p[element].image_type), &(q[element].image_type), 1);

        __int64_t_clone_array(&(p[element].image_data_length), &(q[element].image_data_length), 1);

        q[element].image_data = (uint8_t*) lcm_malloc(sizeof(uint8_t) * q[element].image_data_length);
        __byte_clone_array(p[element].image_data, q[element].image_data, p[element].image_data_length);

        __int8_t_clone_array(&(p[element].camera_model), &(q[element].camera_model), 1);

        __int16_t_clone_array(&(p[element].num_model_coefficients), &(q[element].num_model_coefficients), 1);

        q[element].model_coefficients = (double*) lcm_malloc(sizeof(double) * q[element].num_model_coefficients);
        __double_clone_array(p[element].model_coefficients, q[element].model_coefficients, p[element].num_model_coefficients);

        __int16_t_clone_array(&(p[element].num_integrity), &(q[element].num_integrity), 1);

        q[element].integrity = (aspn23_lcm_type_integrity*) lcm_malloc(sizeof(aspn23_lcm_type_integrity) * q[element].num_integrity);
        __aspn23_lcm_type_integrity_clone_array(p[element].integrity, q[element].integrity, p[element].num_integrity);

    }
    return 0;
}

aspn23_lcm_measurement_image *aspn23_lcm_measurement_image_copy(const aspn23_lcm_measurement_image *p)
{
    aspn23_lcm_measurement_image *q = (aspn23_lcm_measurement_image*) malloc(sizeof(aspn23_lcm_measurement_image));
    __aspn23_lcm_measurement_image_clone_array(p, q, 1);
    return q;
}

void aspn23_lcm_measurement_image_destroy(aspn23_lcm_measurement_image *p)
{
    __aspn23_lcm_measurement_image_decode_array_cleanup(p, 1);
    free(p);
}

int aspn23_lcm_measurement_image_publish(lcm_t *lc, const char *channel, const aspn23_lcm_measurement_image *p)
{
      int max_data_size = aspn23_lcm_measurement_image_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = aspn23_lcm_measurement_image_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _aspn23_lcm_measurement_image_subscription_t {
    aspn23_lcm_measurement_image_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void aspn23_lcm_measurement_image_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    aspn23_lcm_measurement_image p;
    memset(&p, 0, sizeof(aspn23_lcm_measurement_image));
    status = aspn23_lcm_measurement_image_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding aspn23_lcm_measurement_image!!!\n", status);
        return;
    }

    aspn23_lcm_measurement_image_subscription_t *h = (aspn23_lcm_measurement_image_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    aspn23_lcm_measurement_image_decode_cleanup (&p);
}

aspn23_lcm_measurement_image_subscription_t* aspn23_lcm_measurement_image_subscribe (lcm_t *lcm,
                    const char *channel,
                    aspn23_lcm_measurement_image_handler_t f, void *userdata)
{
    aspn23_lcm_measurement_image_subscription_t *n = (aspn23_lcm_measurement_image_subscription_t*)
                       malloc(sizeof(aspn23_lcm_measurement_image_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 aspn23_lcm_measurement_image_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg aspn23_lcm_measurement_image LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int aspn23_lcm_measurement_image_subscription_set_queue_capacity (aspn23_lcm_measurement_image_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int aspn23_lcm_measurement_image_unsubscribe(lcm_t *lcm, aspn23_lcm_measurement_image_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe aspn23_lcm_measurement_image_handler %p!\n", (void*)hid);
        return -1;
    }
    free (hid);
    return 0;
}

