// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MetadataMagneticField.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MetadataMagneticField.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MetadataMagneticField::MetadataMagneticField()
{
}

MetadataMagneticField::~MetadataMagneticField()
{
}

MetadataMagneticField::MetadataMagneticField(
        const MetadataMagneticField& x)
{
    m_info = x.m_info;
    m_time_of_validity = x.m_time_of_validity;
    m_mounting = x.m_mounting;
    m_num_meas = x.m_num_meas;
    m_k = x.m_k;
    m_b = x.m_b;
}

MetadataMagneticField::MetadataMagneticField(
        MetadataMagneticField&& x) noexcept
{
    m_info = std::move(x.m_info);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_mounting = std::move(x.m_mounting);
    m_num_meas = x.m_num_meas;
    m_k = std::move(x.m_k);
    m_b = std::move(x.m_b);
}

MetadataMagneticField& MetadataMagneticField::operator =(
        const MetadataMagneticField& x)
{

    m_info = x.m_info;
    m_time_of_validity = x.m_time_of_validity;
    m_mounting = x.m_mounting;
    m_num_meas = x.m_num_meas;
    m_k = x.m_k;
    m_b = x.m_b;
    return *this;
}

MetadataMagneticField& MetadataMagneticField::operator =(
        MetadataMagneticField&& x) noexcept
{

    m_info = std::move(x.m_info);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_mounting = std::move(x.m_mounting);
    m_num_meas = x.m_num_meas;
    m_k = std::move(x.m_k);
    m_b = std::move(x.m_b);
    return *this;
}

bool MetadataMagneticField::operator ==(
        const MetadataMagneticField& x) const
{
    return (m_info == x.m_info &&
           m_time_of_validity == x.m_time_of_validity &&
           m_mounting == x.m_mounting &&
           m_num_meas == x.m_num_meas &&
           m_k == x.m_k &&
           m_b == x.m_b);
}

bool MetadataMagneticField::operator !=(
        const MetadataMagneticField& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member info
 * @param _info New value to be copied in member info
 */
void MetadataMagneticField::info(
        const aspn23_dds::TypeMetadataheader& _info)
{
    m_info = _info;
}

/*!
 * @brief This function moves the value in member info
 * @param _info New value to be moved in member info
 */
void MetadataMagneticField::info(
        aspn23_dds::TypeMetadataheader&& _info)
{
    m_info = std::move(_info);
}

/*!
 * @brief This function returns a constant reference to member info
 * @return Constant reference to member info
 */
const aspn23_dds::TypeMetadataheader& MetadataMagneticField::info() const
{
    return m_info;
}

/*!
 * @brief This function returns a reference to member info
 * @return Reference to member info
 */
aspn23_dds::TypeMetadataheader& MetadataMagneticField::info()
{
    return m_info;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MetadataMagneticField::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MetadataMagneticField::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MetadataMagneticField::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MetadataMagneticField::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function copies the value in member mounting
 * @param _mounting New value to be copied in member mounting
 */
void MetadataMagneticField::mounting(
        const aspn23_dds::TypeMounting& _mounting)
{
    m_mounting = _mounting;
}

/*!
 * @brief This function moves the value in member mounting
 * @param _mounting New value to be moved in member mounting
 */
void MetadataMagneticField::mounting(
        aspn23_dds::TypeMounting&& _mounting)
{
    m_mounting = std::move(_mounting);
}

/*!
 * @brief This function returns a constant reference to member mounting
 * @return Constant reference to member mounting
 */
const aspn23_dds::TypeMounting& MetadataMagneticField::mounting() const
{
    return m_mounting;
}

/*!
 * @brief This function returns a reference to member mounting
 * @return Reference to member mounting
 */
aspn23_dds::TypeMounting& MetadataMagneticField::mounting()
{
    return m_mounting;
}


/*!
 * @brief This function sets a value in member num_meas
 * @param _num_meas New value for member num_meas
 */
void MetadataMagneticField::num_meas(
        uint8_t _num_meas)
{
    m_num_meas = _num_meas;
}

/*!
 * @brief This function returns the value of member num_meas
 * @return Value of member num_meas
 */
uint8_t MetadataMagneticField::num_meas() const
{
    return m_num_meas;
}

/*!
 * @brief This function returns a reference to member num_meas
 * @return Reference to member num_meas
 */
uint8_t& MetadataMagneticField::num_meas()
{
    return m_num_meas;
}


/*!
 * @brief This function copies the value in member k
 * @param _k New value to be copied in member k
 */
void MetadataMagneticField::k(
        const eprosima::fastcdr::optional<std::vector<double>>& _k)
{
    m_k = _k;
}

/*!
 * @brief This function moves the value in member k
 * @param _k New value to be moved in member k
 */
void MetadataMagneticField::k(
        eprosima::fastcdr::optional<std::vector<double>>&& _k)
{
    m_k = std::move(_k);
}

/*!
 * @brief This function returns a constant reference to member k
 * @return Constant reference to member k
 */
const eprosima::fastcdr::optional<std::vector<double>>& MetadataMagneticField::k() const
{
    return m_k;
}

/*!
 * @brief This function returns a reference to member k
 * @return Reference to member k
 */
eprosima::fastcdr::optional<std::vector<double>>& MetadataMagneticField::k()
{
    return m_k;
}


/*!
 * @brief This function copies the value in member b
 * @param _b New value to be copied in member b
 */
void MetadataMagneticField::b(
        const eprosima::fastcdr::optional<std::vector<double>>& _b)
{
    m_b = _b;
}

/*!
 * @brief This function moves the value in member b
 * @param _b New value to be moved in member b
 */
void MetadataMagneticField::b(
        eprosima::fastcdr::optional<std::vector<double>>&& _b)
{
    m_b = std::move(_b);
}

/*!
 * @brief This function returns a constant reference to member b
 * @return Constant reference to member b
 */
const eprosima::fastcdr::optional<std::vector<double>>& MetadataMagneticField::b() const
{
    return m_b;
}

/*!
 * @brief This function returns a reference to member b
 * @return Reference to member b
 */
eprosima::fastcdr::optional<std::vector<double>>& MetadataMagneticField::b()
{
    return m_b;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MetadataMagneticFieldCdrAux.ipp"

