// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MetadataMagneticField.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_METADATAMAGNETICFIELD_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_METADATAMAGNETICFIELD_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeTimestamp.h"
#include "TypeMetadataheader.h"
#include "TypeMounting.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(METADATAMAGNETICFIELD_SOURCE)
#define METADATAMAGNETICFIELD_DllAPI __declspec( dllexport )
#else
#define METADATAMAGNETICFIELD_DllAPI __declspec( dllimport )
#endif // METADATAMAGNETICFIELD_SOURCE
#else
#define METADATAMAGNETICFIELD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define METADATAMAGNETICFIELD_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {





/*!
 * @brief This class represents the structure MetadataMagneticField defined by the user in the IDL file.
 * @ingroup MetadataMagneticField
 */
class MetadataMagneticField
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MetadataMagneticField();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MetadataMagneticField();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MetadataMagneticField that will be copied.
     */
    eProsima_user_DllExport MetadataMagneticField(
            const MetadataMagneticField& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MetadataMagneticField that will be copied.
     */
    eProsima_user_DllExport MetadataMagneticField(
            MetadataMagneticField&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MetadataMagneticField that will be copied.
     */
    eProsima_user_DllExport MetadataMagneticField& operator =(
            const MetadataMagneticField& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MetadataMagneticField that will be copied.
     */
    eProsima_user_DllExport MetadataMagneticField& operator =(
            MetadataMagneticField&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MetadataMagneticField object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MetadataMagneticField& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MetadataMagneticField object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MetadataMagneticField& x) const;

    /*!
     * @brief This function copies the value in member info
     * @param _info New value to be copied in member info
     */
    eProsima_user_DllExport void info(
            const aspn23_dds::TypeMetadataheader& _info);

    /*!
     * @brief This function moves the value in member info
     * @param _info New value to be moved in member info
     */
    eProsima_user_DllExport void info(
            aspn23_dds::TypeMetadataheader&& _info);

    /*!
     * @brief This function returns a constant reference to member info
     * @return Constant reference to member info
     */
    eProsima_user_DllExport const aspn23_dds::TypeMetadataheader& info() const;

    /*!
     * @brief This function returns a reference to member info
     * @return Reference to member info
     */
    eProsima_user_DllExport aspn23_dds::TypeMetadataheader& info();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function copies the value in member mounting
     * @param _mounting New value to be copied in member mounting
     */
    eProsima_user_DllExport void mounting(
            const aspn23_dds::TypeMounting& _mounting);

    /*!
     * @brief This function moves the value in member mounting
     * @param _mounting New value to be moved in member mounting
     */
    eProsima_user_DllExport void mounting(
            aspn23_dds::TypeMounting&& _mounting);

    /*!
     * @brief This function returns a constant reference to member mounting
     * @return Constant reference to member mounting
     */
    eProsima_user_DllExport const aspn23_dds::TypeMounting& mounting() const;

    /*!
     * @brief This function returns a reference to member mounting
     * @return Reference to member mounting
     */
    eProsima_user_DllExport aspn23_dds::TypeMounting& mounting();


    /*!
     * @brief This function sets a value in member num_meas
     * @param _num_meas New value for member num_meas
     */
    eProsima_user_DllExport void num_meas(
            uint8_t _num_meas);

    /*!
     * @brief This function returns the value of member num_meas
     * @return Value of member num_meas
     */
    eProsima_user_DllExport uint8_t num_meas() const;

    /*!
     * @brief This function returns a reference to member num_meas
     * @return Reference to member num_meas
     */
    eProsima_user_DllExport uint8_t& num_meas();


    /*!
     * @brief This function copies the value in member k
     * @param _k New value to be copied in member k
     */
    eProsima_user_DllExport void k(
            const eprosima::fastcdr::optional<std::vector<double>>& _k);

    /*!
     * @brief This function moves the value in member k
     * @param _k New value to be moved in member k
     */
    eProsima_user_DllExport void k(
            eprosima::fastcdr::optional<std::vector<double>>&& _k);

    /*!
     * @brief This function returns a constant reference to member k
     * @return Constant reference to member k
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<std::vector<double>>& k() const;

    /*!
     * @brief This function returns a reference to member k
     * @return Reference to member k
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<std::vector<double>>& k();


    /*!
     * @brief This function copies the value in member b
     * @param _b New value to be copied in member b
     */
    eProsima_user_DllExport void b(
            const eprosima::fastcdr::optional<std::vector<double>>& _b);

    /*!
     * @brief This function moves the value in member b
     * @param _b New value to be moved in member b
     */
    eProsima_user_DllExport void b(
            eprosima::fastcdr::optional<std::vector<double>>&& _b);

    /*!
     * @brief This function returns a constant reference to member b
     * @return Constant reference to member b
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<std::vector<double>>& b() const;

    /*!
     * @brief This function returns a reference to member b
     * @return Reference to member b
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<std::vector<double>>& b();

private:

    aspn23_dds::TypeMetadataheader m_info;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    aspn23_dds::TypeMounting m_mounting;
    uint8_t m_num_meas{0};
    eprosima::fastcdr::optional<std::vector<double>> m_k;
    eprosima::fastcdr::optional<std::vector<double>> m_b;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_METADATAMAGNETICFIELD_H_



