// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeMounting.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_TYPEMOUNTING_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_TYPEMOUNTING_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TYPEMOUNTING_SOURCE)
#define TYPEMOUNTING_DllAPI __declspec( dllexport )
#else
#define TYPEMOUNTING_DllAPI __declspec( dllimport )
#endif // TYPEMOUNTING_SOURCE
#else
#define TYPEMOUNTING_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TYPEMOUNTING_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {





/*!
 * @brief This class represents the structure TypeMounting defined by the user in the IDL file.
 * @ingroup TypeMounting
 */
class TypeMounting
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TypeMounting();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TypeMounting();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::TypeMounting that will be copied.
     */
    eProsima_user_DllExport TypeMounting(
            const TypeMounting& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::TypeMounting that will be copied.
     */
    eProsima_user_DllExport TypeMounting(
            TypeMounting&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::TypeMounting that will be copied.
     */
    eProsima_user_DllExport TypeMounting& operator =(
            const TypeMounting& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::TypeMounting that will be copied.
     */
    eProsima_user_DllExport TypeMounting& operator =(
            TypeMounting&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeMounting object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TypeMounting& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeMounting object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TypeMounting& x) const;

    /*!
     * @brief This function copies the value in member lever_arm
     * @param _lever_arm New value to be copied in member lever_arm
     */
    eProsima_user_DllExport void lever_arm(
            const std::array<double, 3>& _lever_arm);

    /*!
     * @brief This function moves the value in member lever_arm
     * @param _lever_arm New value to be moved in member lever_arm
     */
    eProsima_user_DllExport void lever_arm(
            std::array<double, 3>&& _lever_arm);

    /*!
     * @brief This function returns a constant reference to member lever_arm
     * @return Constant reference to member lever_arm
     */
    eProsima_user_DllExport const std::array<double, 3>& lever_arm() const;

    /*!
     * @brief This function returns a reference to member lever_arm
     * @return Reference to member lever_arm
     */
    eProsima_user_DllExport std::array<double, 3>& lever_arm();


    /*!
     * @brief This function copies the value in member lever_arm_sigma
     * @param _lever_arm_sigma New value to be copied in member lever_arm_sigma
     */
    eProsima_user_DllExport void lever_arm_sigma(
            const std::array<double, 3>& _lever_arm_sigma);

    /*!
     * @brief This function moves the value in member lever_arm_sigma
     * @param _lever_arm_sigma New value to be moved in member lever_arm_sigma
     */
    eProsima_user_DllExport void lever_arm_sigma(
            std::array<double, 3>&& _lever_arm_sigma);

    /*!
     * @brief This function returns a constant reference to member lever_arm_sigma
     * @return Constant reference to member lever_arm_sigma
     */
    eProsima_user_DllExport const std::array<double, 3>& lever_arm_sigma() const;

    /*!
     * @brief This function returns a reference to member lever_arm_sigma
     * @return Reference to member lever_arm_sigma
     */
    eProsima_user_DllExport std::array<double, 3>& lever_arm_sigma();


    /*!
     * @brief This function copies the value in member orientation_quaternion
     * @param _orientation_quaternion New value to be copied in member orientation_quaternion
     */
    eProsima_user_DllExport void orientation_quaternion(
            const eprosima::fastcdr::optional<std::array<double, 4>>& _orientation_quaternion);

    /*!
     * @brief This function moves the value in member orientation_quaternion
     * @param _orientation_quaternion New value to be moved in member orientation_quaternion
     */
    eProsima_user_DllExport void orientation_quaternion(
            eprosima::fastcdr::optional<std::array<double, 4>>&& _orientation_quaternion);

    /*!
     * @brief This function returns a constant reference to member orientation_quaternion
     * @return Constant reference to member orientation_quaternion
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<std::array<double, 4>>& orientation_quaternion() const;

    /*!
     * @brief This function returns a reference to member orientation_quaternion
     * @return Reference to member orientation_quaternion
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<std::array<double, 4>>& orientation_quaternion();


    /*!
     * @brief This function copies the value in member orientation_tilt_error_covariance
     * @param _orientation_tilt_error_covariance New value to be copied in member orientation_tilt_error_covariance
     */
    eProsima_user_DllExport void orientation_tilt_error_covariance(
            const eprosima::fastcdr::optional<std::vector<double>>& _orientation_tilt_error_covariance);

    /*!
     * @brief This function moves the value in member orientation_tilt_error_covariance
     * @param _orientation_tilt_error_covariance New value to be moved in member orientation_tilt_error_covariance
     */
    eProsima_user_DllExport void orientation_tilt_error_covariance(
            eprosima::fastcdr::optional<std::vector<double>>&& _orientation_tilt_error_covariance);

    /*!
     * @brief This function returns a constant reference to member orientation_tilt_error_covariance
     * @return Constant reference to member orientation_tilt_error_covariance
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<std::vector<double>>& orientation_tilt_error_covariance() const;

    /*!
     * @brief This function returns a reference to member orientation_tilt_error_covariance
     * @return Reference to member orientation_tilt_error_covariance
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<std::vector<double>>& orientation_tilt_error_covariance();

private:

    std::array<double, 3> m_lever_arm{0.0};
    std::array<double, 3> m_lever_arm_sigma{0.0};
    eprosima::fastcdr::optional<std::array<double, 4>> m_orientation_quaternion;
    eprosima::fastcdr::optional<std::vector<double>> m_orientation_tilt_error_covariance;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_TYPEMOUNTING_H_



