// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeMounting.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TypeMounting.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





TypeMounting::TypeMounting()
{
}

TypeMounting::~TypeMounting()
{
}

TypeMounting::TypeMounting(
        const TypeMounting& x)
{
    m_lever_arm = x.m_lever_arm;
    m_lever_arm_sigma = x.m_lever_arm_sigma;
    m_orientation_quaternion = x.m_orientation_quaternion;
    m_orientation_tilt_error_covariance = x.m_orientation_tilt_error_covariance;
}

TypeMounting::TypeMounting(
        TypeMounting&& x) noexcept
{
    m_lever_arm = std::move(x.m_lever_arm);
    m_lever_arm_sigma = std::move(x.m_lever_arm_sigma);
    m_orientation_quaternion = std::move(x.m_orientation_quaternion);
    m_orientation_tilt_error_covariance = std::move(x.m_orientation_tilt_error_covariance);
}

TypeMounting& TypeMounting::operator =(
        const TypeMounting& x)
{

    m_lever_arm = x.m_lever_arm;
    m_lever_arm_sigma = x.m_lever_arm_sigma;
    m_orientation_quaternion = x.m_orientation_quaternion;
    m_orientation_tilt_error_covariance = x.m_orientation_tilt_error_covariance;
    return *this;
}

TypeMounting& TypeMounting::operator =(
        TypeMounting&& x) noexcept
{

    m_lever_arm = std::move(x.m_lever_arm);
    m_lever_arm_sigma = std::move(x.m_lever_arm_sigma);
    m_orientation_quaternion = std::move(x.m_orientation_quaternion);
    m_orientation_tilt_error_covariance = std::move(x.m_orientation_tilt_error_covariance);
    return *this;
}

bool TypeMounting::operator ==(
        const TypeMounting& x) const
{
    return (m_lever_arm == x.m_lever_arm &&
           m_lever_arm_sigma == x.m_lever_arm_sigma &&
           m_orientation_quaternion == x.m_orientation_quaternion &&
           m_orientation_tilt_error_covariance == x.m_orientation_tilt_error_covariance);
}

bool TypeMounting::operator !=(
        const TypeMounting& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member lever_arm
 * @param _lever_arm New value to be copied in member lever_arm
 */
void TypeMounting::lever_arm(
        const std::array<double, 3>& _lever_arm)
{
    m_lever_arm = _lever_arm;
}

/*!
 * @brief This function moves the value in member lever_arm
 * @param _lever_arm New value to be moved in member lever_arm
 */
void TypeMounting::lever_arm(
        std::array<double, 3>&& _lever_arm)
{
    m_lever_arm = std::move(_lever_arm);
}

/*!
 * @brief This function returns a constant reference to member lever_arm
 * @return Constant reference to member lever_arm
 */
const std::array<double, 3>& TypeMounting::lever_arm() const
{
    return m_lever_arm;
}

/*!
 * @brief This function returns a reference to member lever_arm
 * @return Reference to member lever_arm
 */
std::array<double, 3>& TypeMounting::lever_arm()
{
    return m_lever_arm;
}


/*!
 * @brief This function copies the value in member lever_arm_sigma
 * @param _lever_arm_sigma New value to be copied in member lever_arm_sigma
 */
void TypeMounting::lever_arm_sigma(
        const std::array<double, 3>& _lever_arm_sigma)
{
    m_lever_arm_sigma = _lever_arm_sigma;
}

/*!
 * @brief This function moves the value in member lever_arm_sigma
 * @param _lever_arm_sigma New value to be moved in member lever_arm_sigma
 */
void TypeMounting::lever_arm_sigma(
        std::array<double, 3>&& _lever_arm_sigma)
{
    m_lever_arm_sigma = std::move(_lever_arm_sigma);
}

/*!
 * @brief This function returns a constant reference to member lever_arm_sigma
 * @return Constant reference to member lever_arm_sigma
 */
const std::array<double, 3>& TypeMounting::lever_arm_sigma() const
{
    return m_lever_arm_sigma;
}

/*!
 * @brief This function returns a reference to member lever_arm_sigma
 * @return Reference to member lever_arm_sigma
 */
std::array<double, 3>& TypeMounting::lever_arm_sigma()
{
    return m_lever_arm_sigma;
}


/*!
 * @brief This function copies the value in member orientation_quaternion
 * @param _orientation_quaternion New value to be copied in member orientation_quaternion
 */
void TypeMounting::orientation_quaternion(
        const eprosima::fastcdr::optional<std::array<double, 4>>& _orientation_quaternion)
{
    m_orientation_quaternion = _orientation_quaternion;
}

/*!
 * @brief This function moves the value in member orientation_quaternion
 * @param _orientation_quaternion New value to be moved in member orientation_quaternion
 */
void TypeMounting::orientation_quaternion(
        eprosima::fastcdr::optional<std::array<double, 4>>&& _orientation_quaternion)
{
    m_orientation_quaternion = std::move(_orientation_quaternion);
}

/*!
 * @brief This function returns a constant reference to member orientation_quaternion
 * @return Constant reference to member orientation_quaternion
 */
const eprosima::fastcdr::optional<std::array<double, 4>>& TypeMounting::orientation_quaternion() const
{
    return m_orientation_quaternion;
}

/*!
 * @brief This function returns a reference to member orientation_quaternion
 * @return Reference to member orientation_quaternion
 */
eprosima::fastcdr::optional<std::array<double, 4>>& TypeMounting::orientation_quaternion()
{
    return m_orientation_quaternion;
}


/*!
 * @brief This function copies the value in member orientation_tilt_error_covariance
 * @param _orientation_tilt_error_covariance New value to be copied in member orientation_tilt_error_covariance
 */
void TypeMounting::orientation_tilt_error_covariance(
        const eprosima::fastcdr::optional<std::vector<double>>& _orientation_tilt_error_covariance)
{
    m_orientation_tilt_error_covariance = _orientation_tilt_error_covariance;
}

/*!
 * @brief This function moves the value in member orientation_tilt_error_covariance
 * @param _orientation_tilt_error_covariance New value to be moved in member orientation_tilt_error_covariance
 */
void TypeMounting::orientation_tilt_error_covariance(
        eprosima::fastcdr::optional<std::vector<double>>&& _orientation_tilt_error_covariance)
{
    m_orientation_tilt_error_covariance = std::move(_orientation_tilt_error_covariance);
}

/*!
 * @brief This function returns a constant reference to member orientation_tilt_error_covariance
 * @return Constant reference to member orientation_tilt_error_covariance
 */
const eprosima::fastcdr::optional<std::vector<double>>& TypeMounting::orientation_tilt_error_covariance() const
{
    return m_orientation_tilt_error_covariance;
}

/*!
 * @brief This function returns a reference to member orientation_tilt_error_covariance
 * @return Reference to member orientation_tilt_error_covariance
 */
eprosima::fastcdr::optional<std::vector<double>>& TypeMounting::orientation_tilt_error_covariance()
{
    return m_orientation_tilt_error_covariance;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "TypeMountingCdrAux.ipp"

