// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_type_image_feature_h
#define _aspn23_lcm_type_image_feature_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Image feature characteristics
typedef struct _aspn23_lcm_type_image_feature aspn23_lcm_type_image_feature;
struct _aspn23_lcm_type_image_feature
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_type_image_feature;

    /**
     * Description: Value representing the magnitude of the response of the keypoint detection
     * algorithm used to locate this keypoint in the image.
     * Units: none
     */
    double     response;

    /**
     * Description: Value representing the orientation of the detected keypoint, as measured relative
     * to the image coordinate system (radians, clockwise). Metadata flag determines if this field is
     * calculated by the current keypoint detector.
     * Units: rad
     */
    double     orientation;

    /**
     * Description: Effective size (pixels) of the detected keypoint. This field takes into
     * consideration the octave and kernel used to localize the keypoint, and normalizes to the original
     * size of the image.
     * Units: pixels
     */
    double     size;

    /**
     * Description: ID that ties the detected keypoint to a class or group of keypoints.
     * Units: none
     */
    int32_t    class_id;

    /**
     * Description: Octave or pyramid layer from which the detected keypoint was extracted.
     * Units: none
     */
    int32_t    octave;

    /**
     * Description: Size of the descriptor in bytes.
     * Units: none
     */
    int32_t    descriptor_size;

    /**
     * Description: Feature descriptor.
     * Units: none
     * LCM Type: byte[descriptor_size]
     */
    uint8_t    *descriptor;
};

/**
 * Create a deep copy of a aspn23_lcm_type_image_feature.
 * When no longer needed, destroy it with aspn23_lcm_type_image_feature_destroy()
 */
aspn23_lcm_type_image_feature* aspn23_lcm_type_image_feature_copy(const aspn23_lcm_type_image_feature* to_copy);

/**
 * Destroy an instance of aspn23_lcm_type_image_feature created by aspn23_lcm_type_image_feature_copy()
 */
void aspn23_lcm_type_image_feature_destroy(aspn23_lcm_type_image_feature* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_type_image_feature_subscription_t aspn23_lcm_type_image_feature_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_type_image_feature is received.
 */
typedef void(*aspn23_lcm_type_image_feature_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_type_image_feature *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_type_image_feature using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_type_image_feature_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_type_image_feature *msg);

/**
 * Subscribe to messages of type aspn23_lcm_type_image_feature using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_type_image_feature_subscription_t* aspn23_lcm_type_image_feature_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_type_image_feature_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_type_image_feature_subscribe()
 */
int aspn23_lcm_type_image_feature_unsubscribe(lcm_t *lcm, aspn23_lcm_type_image_feature_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_type_image_feature_subscription_set_queue_capacity(
    aspn23_lcm_type_image_feature_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_type_image_feature into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_type_image_feature_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_type_image_feature_encode(void *buf, int offset, int maxlen, const aspn23_lcm_type_image_feature *p);

/**
 * Decode a message of type aspn23_lcm_type_image_feature from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_type_image_feature_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_type_image_feature_decode(const void *buf, int offset, int maxlen, aspn23_lcm_type_image_feature *msg);

/**
 * Release resources allocated by aspn23_lcm_type_image_feature_decode()
 * @return 0
 */
int aspn23_lcm_type_image_feature_decode_cleanup(aspn23_lcm_type_image_feature *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_type_image_feature
 */
int aspn23_lcm_type_image_feature_encoded_size(const aspn23_lcm_type_image_feature *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_type_image_feature_get_hash(void);
uint64_t __aspn23_lcm_type_image_feature_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_type_image_feature_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_type_image_feature *p, int elements);
int __aspn23_lcm_type_image_feature_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_type_image_feature *p, int elements);
int __aspn23_lcm_type_image_feature_decode_array_cleanup(aspn23_lcm_type_image_feature *p, int elements);
int __aspn23_lcm_type_image_feature_encoded_array_size(const aspn23_lcm_type_image_feature *p, int elements);
int __aspn23_lcm_type_image_feature_clone_array(const aspn23_lcm_type_image_feature *p, aspn23_lcm_type_image_feature *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
