// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_measurement_image_h
#define _aspn23_lcm_measurement_image_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "aspn23_lcm_type_header.h"
#include "aspn23_lcm_type_timestamp.h"
#include "aspn23_lcm_type_integrity.h"
/// Windows Bitmaps
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_BMP 0
/// Portable Network Graphics
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_PNG 1
/// Joint Photographic Experts Group
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_JPG 2
/// Tag Image File Format
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_TIFF 3
/// Single channel raw gray scale image. One byte per pixel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY8 4
/// Three channel raw RGB image. One byte per pixel per channel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGB8 5
/// Three channel raw BGR image. One byte per pixel per channel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGR8 6
/// Four channel raw RGBA image. One byte per pixel per channel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGBA8 7
/// Four channel raw BGRA image. One byte per pixel per channel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGRA8 8
/// Single channel raw gray scale image. Two bytes per pixel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY16 9
/// Single channel raw gray scale image. Eight bytes per pixel.
#define ASPN23_LCM_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAYFLOAT64 10

/**
 * A 10 parameter model, 4 parameters composing the 2D focal length fc = (fx, fy) and camera
 * principal point cc = (cx, cy) in pixels, a model of radial and tangential distortion specified using
 * the 5 parameters (kc1, kc2, kc3, kc4, kc5). And the skew parameter, alpha_c. Mapping from 3D points
 * in the world to 2D points in the image is described at
 * http://www.vision.caltech.edu/bouguetj/calib_doc/htmls/parameters.html
 */
#define ASPN23_LCM_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_PINHOLE_PLUMB_BOB 0

/**
 * A 4 parameter model, modeling only the the 2D focal length fc = (fx, fy) and camera principal
 * point cc = (cx, cy). Effectively using the same model as described in described at
 * http://www.vision.caltech.edu/bouguetj/calib_doc/htmls/parameters.html, with all distortion and skew
 * parameters zeroed out
 */
#define ASPN23_LCM_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_LINEAR_MODEL 1

/// 2D Raster Image
typedef struct _aspn23_lcm_measurement_image aspn23_lcm_measurement_image;
struct _aspn23_lcm_measurement_image
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_measurement_image;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    aspn23_lcm_type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    aspn23_lcm_type_timestamp time_of_validity;

    /**
     * Description: The number of pixel rows in this image.
     * Units: pixels
     */
    int64_t    height;

    /**
     * Description: The number of pixel columns in this image.
     * Units: pixels
     */
    int64_t    width;

    /**
     * Description: True if the image_data byte order is big endian, false if it is little endian. For
     * raw image_types, this is only applicable for image_types with multi-byte pixels.
     * Units: none
     */
    int8_t     is_bigendian;

    /**
     * Enumerated field which specifies the datatype of the pixels represented in this image.
     * Raw images are stored in row-major order. In multi-channel raw images, the first element
     * contains the first pixel of the first channel, the second element contains the first pixel of the
     * second channel, and so on. The data of each multi-byte pixel should be contiguous within the data
     * array with the endianness defined by the is_bigendian field.
     * Example - 2x2 RAW_RGB8 image_data[0] row1 col1 chanR image_data[1] row1 col1 chanG image_data[2]
     * row1 col1 chanB image_data[3] row1 col2 chanR image_data[4] row1 col2 chanG image_data[5] row1 col2
     * chanB image_data[6] row2 col1 chanR image_data[7] row2 col1 chanG image_data[8] row2 col1 chanB
     * image_data[9] row2 col2 chanR image_data[10] row2 col2 chanG image_data[11] row2 col2 chanB
     * Example - 2x2 RAW_GRAY16, is_bigendian = 1 Where byte 1 is the most significant byte (byte1 << 8
     * | byte2): image_data[0] row1 col1 byte1 image_data[1] row1 col1 byte2 image_data[2] row1 col2 byte1
     * image_data[3] row1 col2 byte2 image_data[4] row2 col1 byte1 image_data[5] row2 col1 byte2
     * image_data[6] row2 col2 byte1 image_data[7] row2 col2 byte2
     */
    int8_t     image_type;

    /**
     * Description: Length of the byte array holding the encoded image. For raw image types, this
     * should be equal to height * width * num_channels * bytes_per_pixel.
     * Units: byte
     */
    int64_t    image_data_length;

    /**
     * Description: Stores the encoded image. Interpretation varies based on the image_type.
     * Units: none
     * LCM Type: byte[image_data_length]
     */
    uint8_t    *image_data;

    /**
     * The model used to map 3D points in the world to 2D points on the image plane
     */
    int8_t     camera_model;

    /**
     * Description: The number of coefficients used in camera model.
     * Units: none
     */
    int16_t    num_model_coefficients;

    /**
     * Description: The camera model parameters, size depending on the distortion model.
     * Units: none
     * LCM Type: double[num_model_coefficients]
     */
    double     *model_coefficients;

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    int16_t    num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    aspn23_lcm_type_integrity *integrity;
};

/**
 * Create a deep copy of a aspn23_lcm_measurement_image.
 * When no longer needed, destroy it with aspn23_lcm_measurement_image_destroy()
 */
aspn23_lcm_measurement_image* aspn23_lcm_measurement_image_copy(const aspn23_lcm_measurement_image* to_copy);

/**
 * Destroy an instance of aspn23_lcm_measurement_image created by aspn23_lcm_measurement_image_copy()
 */
void aspn23_lcm_measurement_image_destroy(aspn23_lcm_measurement_image* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_measurement_image_subscription_t aspn23_lcm_measurement_image_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_measurement_image is received.
 */
typedef void(*aspn23_lcm_measurement_image_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_measurement_image *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_measurement_image using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_measurement_image_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_measurement_image *msg);

/**
 * Subscribe to messages of type aspn23_lcm_measurement_image using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_measurement_image_subscription_t* aspn23_lcm_measurement_image_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_measurement_image_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_measurement_image_subscribe()
 */
int aspn23_lcm_measurement_image_unsubscribe(lcm_t *lcm, aspn23_lcm_measurement_image_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_measurement_image_subscription_set_queue_capacity(
    aspn23_lcm_measurement_image_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_measurement_image into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_measurement_image_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_image_encode(void *buf, int offset, int maxlen, const aspn23_lcm_measurement_image *p);

/**
 * Decode a message of type aspn23_lcm_measurement_image from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_measurement_image_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_image_decode(const void *buf, int offset, int maxlen, aspn23_lcm_measurement_image *msg);

/**
 * Release resources allocated by aspn23_lcm_measurement_image_decode()
 * @return 0
 */
int aspn23_lcm_measurement_image_decode_cleanup(aspn23_lcm_measurement_image *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_measurement_image
 */
int aspn23_lcm_measurement_image_encoded_size(const aspn23_lcm_measurement_image *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_measurement_image_get_hash(void);
uint64_t __aspn23_lcm_measurement_image_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_measurement_image_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_measurement_image *p, int elements);
int __aspn23_lcm_measurement_image_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_measurement_image *p, int elements);
int __aspn23_lcm_measurement_image_decode_array_cleanup(aspn23_lcm_measurement_image *p, int elements);
int __aspn23_lcm_measurement_image_encoded_array_size(const aspn23_lcm_measurement_image *p, int elements);
int __aspn23_lcm_measurement_image_clone_array(const aspn23_lcm_measurement_image *p, aspn23_lcm_measurement_image *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
