// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_measurement_satnav_subframe_h
#define _aspn23_lcm_measurement_satnav_subframe_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "aspn23_lcm_type_header.h"
#include "aspn23_lcm_type_timestamp.h"
#include "aspn23_lcm_type_satnav_satellite_system.h"
#include "aspn23_lcm_type_integrity.h"
/// satnav navigation data bit subframe.
typedef struct _aspn23_lcm_measurement_satnav_subframe aspn23_lcm_measurement_satnav_subframe;
struct _aspn23_lcm_measurement_satnav_subframe
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_measurement_satnav_subframe;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    aspn23_lcm_type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    aspn23_lcm_type_timestamp time_of_validity;

    /**
     * Description: Message ID provided from the satnav receiver.
     * Units: none
     */
    int64_t    gnss_message_id;

    /**
     * Description: Satellite ID number.
     * Units: none
     */
    int32_t    prn;

    /**
     * Description: Describes the satellite system that generated the subframe.
     * Units: none
     */
    aspn23_lcm_type_satnav_satellite_system satellite_system;

    /**
     * Description: Frequency slot +7 (range from 0-13). Only used for GLONASS.
     * Units: none
     */
    int32_t    freq_slot_id;

    /**
     * Description: Number of bytes of subframe data.
     * Units: none
     */
    int32_t    num_bytes;

    /**
     * Description: num_bytes sized array of raw subframe message collected by the sensor. The
     * underlying type and shape of the data vector is given by satnav_msg_id.
     * Units: none
     * LCM Type: byte[num_bytes]
     */
    uint8_t    *data_vector;

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    int16_t    num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    aspn23_lcm_type_integrity *integrity;
};

/**
 * Create a deep copy of a aspn23_lcm_measurement_satnav_subframe.
 * When no longer needed, destroy it with aspn23_lcm_measurement_satnav_subframe_destroy()
 */
aspn23_lcm_measurement_satnav_subframe* aspn23_lcm_measurement_satnav_subframe_copy(const aspn23_lcm_measurement_satnav_subframe* to_copy);

/**
 * Destroy an instance of aspn23_lcm_measurement_satnav_subframe created by aspn23_lcm_measurement_satnav_subframe_copy()
 */
void aspn23_lcm_measurement_satnav_subframe_destroy(aspn23_lcm_measurement_satnav_subframe* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_measurement_satnav_subframe_subscription_t aspn23_lcm_measurement_satnav_subframe_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_measurement_satnav_subframe is received.
 */
typedef void(*aspn23_lcm_measurement_satnav_subframe_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_measurement_satnav_subframe *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_measurement_satnav_subframe using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_measurement_satnav_subframe_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_measurement_satnav_subframe *msg);

/**
 * Subscribe to messages of type aspn23_lcm_measurement_satnav_subframe using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_measurement_satnav_subframe_subscription_t* aspn23_lcm_measurement_satnav_subframe_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_measurement_satnav_subframe_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_measurement_satnav_subframe_subscribe()
 */
int aspn23_lcm_measurement_satnav_subframe_unsubscribe(lcm_t *lcm, aspn23_lcm_measurement_satnav_subframe_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_measurement_satnav_subframe_subscription_set_queue_capacity(
    aspn23_lcm_measurement_satnav_subframe_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_measurement_satnav_subframe into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_measurement_satnav_subframe_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_satnav_subframe_encode(void *buf, int offset, int maxlen, const aspn23_lcm_measurement_satnav_subframe *p);

/**
 * Decode a message of type aspn23_lcm_measurement_satnav_subframe from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_measurement_satnav_subframe_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_satnav_subframe_decode(const void *buf, int offset, int maxlen, aspn23_lcm_measurement_satnav_subframe *msg);

/**
 * Release resources allocated by aspn23_lcm_measurement_satnav_subframe_decode()
 * @return 0
 */
int aspn23_lcm_measurement_satnav_subframe_decode_cleanup(aspn23_lcm_measurement_satnav_subframe *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_measurement_satnav_subframe
 */
int aspn23_lcm_measurement_satnav_subframe_encoded_size(const aspn23_lcm_measurement_satnav_subframe *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_measurement_satnav_subframe_get_hash(void);
uint64_t __aspn23_lcm_measurement_satnav_subframe_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_measurement_satnav_subframe_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_measurement_satnav_subframe *p, int elements);
int __aspn23_lcm_measurement_satnav_subframe_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_measurement_satnav_subframe *p, int elements);
int __aspn23_lcm_measurement_satnav_subframe_decode_array_cleanup(aspn23_lcm_measurement_satnav_subframe *p, int elements);
int __aspn23_lcm_measurement_satnav_subframe_encoded_array_size(const aspn23_lcm_measurement_satnav_subframe *p, int elements);
int __aspn23_lcm_measurement_satnav_subframe_clone_array(const aspn23_lcm_measurement_satnav_subframe *p, aspn23_lcm_measurement_satnav_subframe *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
